apiVersion: v1
kind: Service
metadata:
  name: echo-app-service
  labels:
    app: echo-app
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30008
      targetPort: 8080
  selector:
    app: echo-app