apiVersion: v1
kind: Pod
metadata:
  name: echo-server
  labels:
    app: echo-server
    tier: backend
spec:
  containers:
    - name: echo-server
      image: localhost:32000/sboot/echo-server:latest
      imagePullPolicy: IfNotPresent
  restartPolicy: Always





