apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-container-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      imagePullPolicy: IfNotPresent
    - name: busybox-container
      image: localhost:32000/busybox
      command: ["watch", "wget", "-qO-", "localhost"]

  restartPolicy: Always
