apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvstore
spec:
  selector:
    matchLabels:
      app: kvstore
  replicas: 1
  template:
    metadata:
      labels:
        app: kvstore
    spec:
      containers:
        - name: kvstore
          image: abhirockzz/kvstore:latest
          volumeMounts:
            - mountPath: /data
              name: nfs-volume
          ports:
            - containerPort: 8080
      volumes:
        - name: nfs-volume
          nfs:
            path: /
            server: 10.152.183.213
---
apiVersion: v1
kind: Service
metadata:
  name: kvstore-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
  selector:
    app: kvstore