apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: development-dynamic